### ISSUE TITLE
Локально автотест падает

### ISSUE THREAD

**Issue by KaterinaRekiyan** [KaterinaRekiyan/Patterns1#1]
### Критичность
Значительный (Major)
### Окружение
Ноутбук DELL Vostro 3558, Windows 10 (64-bit), IntelliJ IDEA Community Edition 2022.2.3, Java: Open JDK 11, selenide:6.12.2
### Описание
Падение автотеста при запуске его в IntelliJ IDEA
### Шаги воспроизведения:
1. Перейти в IntelliJ IDEA в [проект](https://github.com/KaterinaRekiyan/Patterns1)
2. Запустить jar-файл командой: java -jar artifacts/app-card-delivery.jar
3. Запустить тест командой: ./gradlew clean test 

### Ожидаемый результат
test success
### Фактический результат 
 test failed

### Скриншоты
![image](https://user-images.githubusercontent.com/113500983/229273614-19f175d5-c2e8-4112-909a-e520274f7a10.png)
![image](https://user-images.githubusercontent.com/113500983/229273681-f42ab5ce-ffe8-4f8e-9e7b-74782683ee17.png)

**Comment by andrew-pahomov** [comment]
Прошу добавить скрины терминала с запущенным SUT

**Comment by andrew-pahomov** [comment]
В репорт прошу добавить описание окружения. Здесь https://github.com/KaterinaRekiyan/Patterns1/blob/7009a70db504e57c7b8af5ef6e7cdf655e487d75/build.gradle#L28 давайте попробуем указать версию библиотеки 6.12.2

**Comment by KaterinaRekiyan** [comment]
указала версию библиотеки selenide:6.12.2 - не помогло

**Comment by KaterinaRekiyan** [comment]
проблема решена
